name: test
on:
  push:
    branches: [master]
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  yarn-ci:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install libicu60
        run: wget -q http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu60_60.2-3ubuntu3.2_amd64.deb && sudo apt install ./libicu60_60.2-3ubuntu3.2_amd64.deb
      - name: Install eosio
        run: wget -q https://github.com/eosio/eos/releases/download/v2.2.0-rc1/eosio_2.2.0-rc1-ubuntu-20.04_amd64.deb && sudo apt install ./eosio_2.2.0-rc1-ubuntu-20.04_amd64.deb
      - name: Install eosio.cdt
        run: wget -q https://github.com/EOSIO/eosio.cdt/releases/download/v1.8.1/eosio.cdt_1.8.1-1-ubuntu-20.04_amd64.deb && sudo apt install ./eosio.cdt_1.8.1-1-ubuntu-20.04_amd64.deb

      - name: 'Enable corepack'
        run: corepack enable

      - name: 'Install Foundry'
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: 'Install'
        run: yarn install

      - name: 'Build'
        run: yarn build

      - name: 'Lint'
        run: yarn lint

      - name: 'Test'
        run: yarn test
